site_name: Wiki
site_url: https://globox1997.github.io/wiki/
site_description: 'Globox_Z Wiki'
theme:
  name: material
  custom_dir: overrides
  logo: assets/general/icons/website_icon.png
  favicon: assets/general/icons/website_icon.png
  language: en
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - social
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: timeago
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Globox1997
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cV4cJyGXqF
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/globox_z
  analytics:
    provider: google
    property: G-PBXPTBWXFR
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
  projects:
    docs:
        repo: https://github.com/Globox1997/wiki
        name: Globox_Z Wiki
    additionz:
        repo: https://github.com/Globox1997/AdditionZ
        name: AdditionZ
    adventurez:
        repo: https://github.com/Globox1997/AdventureZ
        name: AdventureZ


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - pymdownx.critic

extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 - <a href="https://github.com/Globox1997">Globox_Z</a> - <a href="#__consent">Change Cookie Settings</a>

nav:
  - Home:
    - index.md
  - About:
    - about/credits.md
    - about/licensing.md
    - about/support.md
  - Mods:
    - mods/index.md
    - AdditionZ:
      - mods/AdditionZ/index.md
      - Features:
        - mods/AdditionZ/Features/index.md
      - Items:
        - mods/AdditionZ/Items/Totem_of_Non_Breaking.md
      - Enchantments:
        - mods/AdditionZ/Enchantments/Block_Piercing.md
        - mods/AdditionZ/Enchantments/Curse_of_Inaccuracy.md
        - mods/AdditionZ/Enchantments/Dexterity.md
        - mods/AdditionZ/Enchantments/Eagle_Eyed.md
        - mods/AdditionZ/Enchantments/Stampede.md
    - AdventureZ:
      - mods/AdventureZ/index.md
      - Entities:
        - mods/AdventureZ/Entities/Amethyst_Golem.md
        - mods/AdventureZ/Entities/Blaze_Guardian.md
        - mods/AdventureZ/Entities/Brown_Fungus.md
        - mods/AdventureZ/Entities/Deer.md
        - mods/AdventureZ/Entities/Desert_Rhino.md
        - mods/AdventureZ/Entities/Dragon.md
        - mods/AdventureZ/Entities/Ender_Whale.md
        - mods/AdventureZ/Entities/Enderwarthog.md
        - mods/AdventureZ/Entities/Iguana.md
        - mods/AdventureZ/Entities/Mammoth.md
        - mods/AdventureZ/Entities/Necromancer.md
        - mods/AdventureZ/Entities/Nightmare.md
        - mods/AdventureZ/Entities/Orc.md
        - mods/AdventureZ/Entities/Piglin_Beast.md
        - mods/AdventureZ/Entities/Red_Fungus.md
        - mods/AdventureZ/Entities/Shaman.md
        - mods/AdventureZ/Entities/Skeleton_Vanguard.md
        - mods/AdventureZ/Entities/Small_Stone_Golem.md
        - mods/AdventureZ/Entities/Soul_Reaper.md
        - mods/AdventureZ/Entities/Stone_Golem.md
        - mods/AdventureZ/Entities/Summoner.md
        - mods/AdventureZ/Entities/The_Eye.md
        - mods/AdventureZ/Entities/Wither_Puppet.md
      - Items:
        - mods/AdventureZ/Items/Gilded_Blackstone_Shard.md
        - mods/AdventureZ/Items/Blackstone_Golem_Heart.md
        - mods/AdventureZ/Items/Blackstones_Arm.md
        - mods/AdventureZ/Items/Gilded_Netherite_Fragment.md
        - mods/AdventureZ/Items/Prime_Eye.md
        - mods/AdventureZ/Items/Orc_Skin.md
        - mods/AdventureZ/Items/Dragon_Saddle.md
        - mods/AdventureZ/Items/Source_Stone.md
        - mods/AdventureZ/Items/Chorus_Fruit_on_a_Stick.md
        - mods/AdventureZ/Items/Ender_Flute.md
        - mods/AdventureZ/Items/Iguana_Hide.md
        - mods/AdventureZ/Items/Mammoth_Fur.md
        - mods/AdventureZ/Items/Ender_Whale_Skin.md
        - mods/AdventureZ/Items/Ivory_Arrow.md
        - mods/AdventureZ/Items/Mammoth_Tusk.md
        - mods/AdventureZ/Items/Rhino_Leather.md
        - mods/AdventureZ/Items/Warthog_Shell_Piece.md
        - mods/AdventureZ/Items/Handbook.md
        - mods/AdventureZ/Items/Mammoth_Meat.md
        - mods/AdventureZ/Items/Cooked_Mammoth_Meat.md
        - mods/AdventureZ/Items/Iguana_Meat.md
        - mods/AdventureZ/Items/Cooked_Iguana_Meat.md
        - mods/AdventureZ/Items/Ender_Whale_Meat.md
        - mods/AdventureZ/Items/Cooked_Ender_Whale_Meat.md
        - mods/AdventureZ/Items/Rhino_Meat.md
        - mods/AdventureZ/Items/Cooked_Rhino_Meat.md
        - mods/AdventureZ/Items/Raw_Venison.md
        - mods/AdventureZ/Items/Cooked_Venison.md
        - mods/AdventureZ/Items/Warthog_Meat.md
        - mods/AdventureZ/Items/Cooked_Warthog_Meat.md
        - mods/AdventureZ/Items/Gilded_Netherite_Helmet.md
        - mods/AdventureZ/Items/Gilded_Netherite_Chestplate.md
        - mods/AdventureZ/Items/Gilded_Netherite_Leggings.md
        - mods/AdventureZ/Items/Gilded_Netherite_Boots.md
      - Blocks:
        - mods/AdventureZ/Blocks/Stone_Holder.md
        - mods/AdventureZ/Blocks/Piglin_Flag.md
        - mods/AdventureZ/Blocks/Shadow_Chest.md
      - Structures:
        - mods/AdventureZ/Structures/Blackstone_Altar.md
    - BackSlot:
      - mods/BackSlot/index.md
